### ISSUE TITLE
This script should be moved to TheAlgorithms/.github

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/scripts#2]
If this script is to be used by multiple language repos then it should be moved to https://github.com/TheAlgorithms/.github

**Comment by Panquesito7** [comment]
@maltejur?

**Comment by maltejur** [comment]
From my understanding the `.github` repository contains the default files for a new repository. But the script in this repository shouldn't just be placed into a new repository, it has to be integrated manually via a workflow.

But since the website doesn't require the `directory.md` anymore, I think the more important question is if all of the repositories still even need those files or this script. I don't think any repository actually directly uses this repository, so maybe we should just delete it.

**Comment by cclauss** [comment]
For Python, I would like to keep `directory.md` because many people come to the code via GitHub, not via the website.
